# Generated by Django 5.0 on 2023-12-06 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_postcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='comment_text',
            new_name='comment',
        ),
    ]
